# Generated by Django 4.0.1 on 2022-02-16 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Корзины',
                'verbose_name_plural': 'Корзины',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('size', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('creation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='QuantityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzahome.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzahome.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=255, verbose_name='Квартира')),
                ('number', models.IntegerField(verbose_name='Телефон для связи')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('in_work', models.BooleanField(default=False, verbose_name='В работе')),
                ('finally_price', models.IntegerField(default=0)),
                ('product', models.ManyToManyField(to='pizzahome.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzahome.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='pizzahome.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
